### ISSUE TITLE
System.IO.DirectoryNotFoundException during app launch

### ISSUE THREAD

**Issue by wanderzirkus** [plainionist/Plainion.DrawVista#3]
Hi,

when running the application after following the installation steps of the ReadMe an exception is thrown.

I believe the corresponding code should migrate data from an old file based document store to the currently used SQLite based one. It seems that it assumes the store directory always exists.
Imho this is a bug, which could easily be fixed by checking if the directory 'C:\ProgramData\Plainion.DrawVista\store' exists before attempting the migration task.

I can make PR if you want, just let me know.

The workaround is to just create the directory in path 'C:\ProgramData\Plainion.DrawVista\store'.

```
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\ProgramData\Plainion.DrawVista\store'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Plainion.DrawVista.IO.FileSystemDocumentStore.GetPageNames() in D:\Workspace\GitHub\Plainion.DrawVista\src\Plainion.DrawVista\IO\FileSystemDocumentStore.cs:line 15
   at Program.<Main>$(String[] args) in D:\Workspace\GitHub\Plainion.DrawVista\src\Plainion.DrawVista\Program.cs:line 33
```

**Comment by plainionist** [comment]
I added you as contributor - feel free to submit the fix directly - thx!

**Comment by wanderzirkus** [comment]
Thank you very much, the issue should be solved with https://github.com/plainionist/Plainion.DrawVista/commit/3fba21f18dff90390acba9c4b5126723bf1f54aa
